import type { Metadata } from "next"
import "./globals.css"
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import CrrgCookie from "@/components/CrrgCookie";
import ScrollToTop from "@/components/ScrollToTop";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        <CrrgCookie />  
        <ScrollToTop />
      </body>
    </html>
  );
}
